# Generated by Django 2.1.4 on 2019-01-03 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=32)),
                ('zodiac_sign', models.CharField(max_length=32)),
                ('stars', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('health', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('crit_chance', models.FloatField()),
                ('crit_damage', models.FloatField()),
                ('efffectiveness', models.FloatField()),
                ('effect_resistance', models.FloatField()),
                ('dual_atk_chance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Skill'),
        ),
    ]
