# Generated by Django 2.1.4 on 2019-01-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_character_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='skill',
        ),
    ]
