# Generated by Django 2.1.4 on 2019-01-03 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_remove_character_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='efffectiveness',
            new_name='effectiveness',
        ),
    ]
