# Generated by Django 2.1.4 on 2019-01-04 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rarity', models.IntegerField()),
                ('exclusive', models.CharField(max_length=255)),
                ('lore_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Artifact_Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=255)),
                ('maximum', models.CharField(max_length=255)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_description', to='artifacts.Artifact')),
            ],
        ),
        migrations.CreateModel(
            name='Artifact_Stat_Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_stat_values', to='artifacts.Artifact')),
            ],
        ),
        migrations.CreateModel(
            name='Artifact_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_stats', to='artifacts.Artifact')),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifact_stat_base', to='artifacts.Artifact_Stat_Values')),
                ('maximum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifact_stat_max', to='artifacts.Artifact_Stat_Values')),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='skill_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifact_description', to='artifacts.Artifact_Description'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifact_stats', to='artifacts.Artifact_Stats'),
        ),
    ]
