# Generated by Django 2.1.4 on 2019-01-04 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact_Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_attack', models.IntegerField()),
                ('base_hp', models.IntegerField()),
                ('max_attack', models.IntegerField()),
                ('max_hp', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='artifact_stat_values',
            name='artifact',
        ),
        migrations.RemoveField(
            model_name='artifact_stats',
            name='artifact',
        ),
        migrations.RemoveField(
            model_name='artifact_stats',
            name='base',
        ),
        migrations.RemoveField(
            model_name='artifact_stats',
            name='maximum',
        ),
        migrations.AlterField(
            model_name='artifact',
            name='stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifact_stats', to='artifacts.Artifact_Stat'),
        ),
        migrations.DeleteModel(
            name='Artifact_Stat_Values',
        ),
        migrations.DeleteModel(
            name='Artifact_Stats',
        ),
        migrations.AddField(
            model_name='artifact_stat',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_stat', to='artifacts.Artifact'),
        ),
    ]
