# Generated by Django 2.1.4 on 2019-01-03 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('souls_aquired', models.IntegerField(blank=True, null=True)),
                ('turns', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('has_burn', models.BooleanField(default=False)),
                ('burn_description', models.CharField(blank=True, max_length=255, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
        ),
    ]
